### ISSUE TITLE
can't make a neon project, thread panicked at 'failed to run "npm install" for neon-sys'

### ISSUE THREAD

**Issue by leshow** [rustbridge/neon#98]
I followed the steps to create a new project from the readme, upon running neon build I get:

```
$ neon build
neon info running cargo
neon info cargo build --release
error: failed to run custom build command for `neon-sys v0.1.10`
process didn't exit successfully: `C:\Users\test\test\native\target\release\build\neon-sys-03671bf25b64d6d\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'failed to run "npm install" for neon-sys', ../src/libcore/option.rs:699
note: Run with `RUST_BACKTRACE=1` for a backtrace.

neon ERR! cargo build failed
```

**Comment by brodeuralexis** [comment]
Same problem on Windows 10 x64, NodeJS 6.3.1 and Rust 1.10.0 (cfcb716cf 2016-07-03).

Here are the commands I executed :
```bash
neon new myproject
cd myproject
npm i
```

**Comment by brodeuralexis** [comment]
Same problem on Windows 10 x64, NodeJS 6.3.1 and Rust 1.10.0 (cfcb716cf 2016-07-03).

Here are the commands I executed :
```bash
neon new myproject
cd myproject
npm i
```

EDIT: Here is the output of `npm i` :
```
$ RUST_BACKTRACE=1 npm i

> nath@0.1.0 install C:\Users\Consultant\code\nath
> neon build

neon info running cargo
neon info cargo build --release
   Compiling neon-sys v0.1.11
error: failed to run custom build command for `neon-sys v0.1.11`
Process didn't exit successfully: `C:\Users\Consultant\code\nath\native\target\release\build\neon-sys-3509514629677365\build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'failed to run "npm install" for neon-sys', ../src/libcore\option.rs:699
stack backtrace:
   0:           0x45c7bc - <unknown>
   1:           0x45bcd7 - <unknown>
   2:           0x421364 - <unknown>
   3:           0x45d865 - <unknown>
   4:           0x4232a5 - <unknown>
   5:           0x45d4cc - <unknown>
   6:           0x470bb5 - <unknown>
   7:           0x495e84 - <unknown>
   8:           0x4025f0 - <unknown>
   9:           0x402288 - <unknown>
  10:           0x40552e - <unknown>
  11:           0x45b49c - <unknown>
  12:           0x46bc78 - <unknown>
  13:           0x45b294 - <unknown>
  14:           0x40556a - <unknown>
  15:           0x4013b4 - <unknown>
  16:           0x4014e7 - <unknown>
  17:     0x7ffe8c108101 - <unknown>

neon ERR! cargo build failed

npm WARN nath@0.1.0 No repository field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! nath@0.1.0 install: `neon build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nath@0.1.0 install script 'neon build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nath package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     neon build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nath
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nath
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Consultant\code\nath\npm-debug.log
```

**Comment by zethra** [comment]
Same problem Windows 10 x64 Node 6.6.0 Rust 1.11.0
Output of `RUST_BACKTRACE=1 npm i`
<pre>

> hello-node@0.1.0 install C:\Users\zethra\Projects\Personal\neon-test\hello-node
> neon build

neon info running cargo
neon info cargo build --release
   Compiling neon-sys v0.1.11
error: failed to run custom build command for `neon-sys v0.1.11`
process didn't exit successfully: `C:\Users\zethra\Projects\Personal\neon-test\hello-node\native\target\release\build\neon-sys-3509514629677365\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'failed to run "npm install" for neon-sys', ../src/libcore\option.rs:699
stack backtrace:
   0:     0x7ff78519a58c - std::rt::lang_start::h162055cb2e4b9fe7
   1:     0x7ff785199b99 - std::rt::lang_start::h162055cb2e4b9fe7
   2:     0x7ff78518186d - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   3:     0x7ff78519cbcb - rust_begin_unwind
   4:     0x7ff785182edf - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   5:     0x7ff78519c80c - rust_begin_unwind
   6:     0x7ff78519ea95 - core::panicking::panic_fmt::h2d3cc8234dde51b4
   7:     0x7ff7851a0054 - core::option::expect_failed::ha6269a58a5455f37
   8:     0x7ff785161a85 - __ImageBase
   9:     0x7ff78519958c - std::rt::lang_start::h162055cb2e4b9fe7
  10:     0x7ff78519d381 - _rust_maybe_catch_panic
  11:     0x7ff7851992c4 - std::rt::lang_start::h162055cb2e4b9fe7
  12:     0x7ff7851a2e60 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  13:     0x7fffee5c8363 - BaseThreadInitThunk

neon ERR! cargo build failed

npm WARN hello-node@0.1.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! hello-node@0.1.0 install: `neon build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello-node@0.1.0 install script 'neon build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hello-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     neon build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hello-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hello-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\zethra\Projects\Personal\neon-test\hello-node\npm-debug.log
</pre>

**Comment by janispritzkau** [comment]
I get the same error on Windows 10. Will this be fixed someday?

**Comment by mqliutie** [comment]
+1

**Comment by kjvalencik** [comment]
This issue is not likely going to be fixed unless a user contributes a fix (which I will happily merge!) for a few reasons. We aren't able to reliably reproduce (it works in CI), none of the core neon team are Windows developers, and `neon-sys` is no longer being actively developed (new projects default to the Node-API backend).
